#!/usr/bin/env node
// scripts/optimize-images.mjs
//
// Converts every source PNG/JPG under `_source/` into a web-optimised WebP
// under `public/work/`, and emits a manifest at `content/images.json`.
//
// Usage: node scripts/optimize-images.mjs   (or `npm run images`)
//
// ---------------------------------------------------------------------------
// TEMPLATE USAGE
// ---------------------------------------------------------------------------
// 1. Where source images go
//    Drop full-resolution artwork into `_source/`. You can either:
//      - dump files loosely at the top level of `_source/` (these become
//        "deck" plates), or
//      - put them inside a subfolder (any depth) whose name starts with a
//        two-digit number, to control which *category* they land in:
//          01_... -> "mood"   (moodboard / concept images)
//          02_... -> "app"    (applications / mock-up presentations)
//          03_... -> "mood"   (menus, brochures, etc. — see PIZZERIA/
//                              REAL_ESTATE special-cases below)
//          04_... -> "cover"  (hero / campaign artwork)
//        Folder name and nesting beyond the leading "NN_" is up to you
//        (e.g. `_source/01_Moodboard_Images/` or a more deeply nested path
//        like `_source/MyDrop/01_Moodboard_Images/` both work).
//
// 2. Filename convention: `PROJECT_NN_Description.png`
//      - `PROJECT`     one or more `_`-joined, ALL-CAPS words identifying the
//                      project. Becomes the output slug, lowercased with
//                      underscores turned into hyphens (`MY_BRAND` -> `my-brand`).
//      - `NN`          a 1-3 digit run number. Controls sort order and is the
//                      first half of the manifest `key` (zero-padded to 2
//                      digits, e.g. `05`).
//      - `Description`  everything after NN. Becomes both the slugified
//                      second half of the manifest `key` and the human-
//                      readable `label` for the plate.
//    If a filename has no numeric segment at all (e.g. `MY_BRAND_Cover.png`),
//    the script falls back to treating every leading ALL-CAPS word as the
//    project prefix, `NN` as `01`, and everything after as the description.
//    If no project prefix can be determined at all, the file still gets
//    processed under a `studio` slug rather than being skipped.
//
// 3. Redirecting a derived slug: `PREFIX_ALIASES` below
//    Sometimes you want several filename prefixes to collapse into one
//    project (e.g. `REAL_ESTATE_OPEN_HOUSE_*` and `REAL_ESTATE_BROCHURE_A_*`
//    should both live under the single `real-estate` project). Add an entry
//    to `PREFIX_ALIASES` for that — you do NOT have to add anything here for
//    the common case where the derived slug is already what you want.
//
// 4. `content/images.json` is fully regenerated by this script. The `key`
//    field it writes for each plate (`<nn>-<description-slug>`, e.g.
//    `05-billboard`) is what `content/projects.json`'s `plates[].key` must
//    match for that plate to pick up a caption/title in the UI. If you
//    rename a source file, update the matching `plates[].key` too.
// ---------------------------------------------------------------------------

import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SOURCE_ROOT = path.join(ROOT, '_source');
const OUTPUT_ROOT = path.join(ROOT, 'public', 'work');
const MANIFEST_PATH = path.join(ROOT, 'content', 'images.json');

const WEBP_OPTIONS = { quality: 80, effort: 5 };
const MAX_EDGE = 1600;
const IMAGE_EXT_RE = /\.(png|jpe?g)$/i;

// Small responsive variant: same quality settings as the full-size WebP, but
// capped at this longest edge. Filename is the full-size filename with
// `-800` inserted before the extension. Skipped entirely (no file, no
// manifest fields) when the full-size output is already at or under this,
// since that would just be a same-size duplicate of the full image.
const SMALL_MAX_EDGE = 800;
const SMALL_SUFFIX = '-800';

// ---------------------------------------------------------------------------
// PREFIX_ALIASES — optional overrides for the automatically-derived project
// slug (see step 3 above). Keys are the slug the naming convention would
// derive on its own; values are the slug you actually want it to land under.
// Add your own entries here as needed — most template users won't need any.
//
// This project needs the four below because several filename prefixes are
// meant to share one project folder.
// ---------------------------------------------------------------------------
const PREFIX_ALIASES = {
  'pizzeria-presentation': 'pizzeria',
  'real-estate-open-house': 'real-estate',
  'real-estate-brochure-a': 'real-estate',
  'real-estate-brochure-b': 'real-estate',
};

// ---------------------------------------------------------------------------
// CATEGORY_OVERRIDES — optional per-prefix category overrides, for the rare
// case where a specific filename prefix should land in a different category
// than its source folder's default (see BULK category table above). Matched
// against the *derived* (pre-alias) prefix, e.g. `PIZZERIA_PRESENTATION`.
//
// This project needs these because the presentation/brochure mock-ups are
// "app" (application) plates that happen to live in the same source folder
// as the "mood" images for their project.
// ---------------------------------------------------------------------------
const CATEGORY_OVERRIDES = [
  { prefix: 'PIZZERIA_PRESENTATION', category: 'app' },
  { prefix: 'REAL_ESTATE_BROCHURE_A', category: 'app' },
  { prefix: 'REAL_ESTATE_BROCHURE_B', category: 'app' },
];

// Numbered-subfolder name prefix -> default category for files inside it.
const CATEGORY_BY_DIR_PREFIX = {
  '01': 'mood',
  '02': 'app',
  '03': 'mood',
  '04': 'cover',
};

// ---------------------------------------------------------------------------
// DECK_SLIDES — optional explicit overrides for loose, top-level files in
// `_source/` whose filenames don't follow the `PROJECT_NN_Description`
// convention (e.g. camera/export timestamp names) and so can't be parsed
// automatically. This is NOT required for a template: any root-level image
// not listed here is still processed — its slug/descriptor is derived from
// its filename the same way as everything else (falling back to a `studio`
// slug if no project can be determined at all). Nothing here throws.
//
// The 14 entries below are this project's own timestamp-named exports, each
// one manually opened and identified:
//
//  - 08_41_15 AM / 08_48_38 AM / 09_43_27 AM(2) / 09_43_35 AM(2)
//      "07 — APPLICATIONS" spreads (Spotify/vinyl/CD/billboard/IG mock-ups)
//      for FADED, JUST PERFECT, WITHOUT ME, CARNIVAL OF RUST respectively.
//  - 10_52_51 AM(1) / 10_52_52 AM(2)
//      PIZZERIA SCHNELL SERVICE mood board, then menu presentation spread.
//  - 12_37_03 PM / 12_39_07 PM
//      Real-estate "Designed For Modern Living" brochure page, then the
//      "Real Estate Open House" flyer.
//  - 01_07_43 PM / 01_07_50 PM
//      SOFIA mood board, then its "07 — PRESENTATIONS" applications spread.
//  - 01_56_05 PM(2) / 01_56_05 PM(3) / 01_56_06 PM(4) / 02_04_11 PM
//      Mood boards for CARNIVAL OF RUST, JUST PERFECT, FADED, WITHOUT ME.
//
// nn is assigned per project in the order each project's slides were
// produced (applications-style spreads were generated in the morning batch,
// mood boards in the afternoon batch for the four band projects).
// ---------------------------------------------------------------------------
const DECK_SLIDES = [
  { file: 'ChatGPT Image Jul 25, 2026, 08_41_15 AM.png', slug: 'faded', nn: '01', descriptor: 'applications', label: 'Applications' },
  { file: 'ChatGPT Image Jul 25, 2026, 08_48_38 AM.png', slug: 'just-perfect', nn: '01', descriptor: 'applications', label: 'Applications' },
  { file: 'ChatGPT Image Jul 25, 2026, 09_43_27 AM (2).png', slug: 'without-me', nn: '01', descriptor: 'applications', label: 'Applications' },
  { file: 'ChatGPT Image Jul 25, 2026, 09_43_35 AM (2).png', slug: 'carnival-of-rust', nn: '01', descriptor: 'applications', label: 'Applications' },
  { file: 'ChatGPT Image Jul 25, 2026, 10_52_51 AM (1).png', slug: 'pizzeria', nn: '01', descriptor: 'mood-board', label: 'Mood Board' },
  { file: 'ChatGPT Image Jul 25, 2026, 10_52_52 AM (2).png', slug: 'pizzeria', nn: '02', descriptor: 'menu-presentation', label: 'Menu Presentation' },
  { file: 'ChatGPT Image Jul 25, 2026, 12_37_03 PM.png', slug: 'real-estate', nn: '01', descriptor: 'modern-living', label: 'Modern Living' },
  { file: 'ChatGPT Image Jul 25, 2026, 12_39_07 PM.png', slug: 'real-estate', nn: '02', descriptor: 'open-house', label: 'Open House' },
  { file: 'ChatGPT Image Jul 25, 2026, 01_07_43 PM.png', slug: 'sofia', nn: '01', descriptor: 'mood-board', label: 'Mood Board' },
  { file: 'ChatGPT Image Jul 25, 2026, 01_07_50 PM.png', slug: 'sofia', nn: '02', descriptor: 'presentations', label: 'Presentations' },
  { file: 'ChatGPT Image Jul 25, 2026, 01_56_05 PM (2).png', slug: 'carnival-of-rust', nn: '02', descriptor: 'mood-board', label: 'Mood Board' },
  { file: 'ChatGPT Image Jul 25, 2026, 01_56_05 PM (3).png', slug: 'just-perfect', nn: '02', descriptor: 'mood-board', label: 'Mood Board' },
  { file: 'ChatGPT Image Jul 25, 2026, 01_56_06 PM (4).png', slug: 'faded', nn: '02', descriptor: 'mood-board', label: 'Mood Board' },
  { file: 'ChatGPT Image Jul 25, 2026, 02_04_11 PM.png', slug: 'without-me', nn: '02', descriptor: 'mood-board', label: 'Mood Board' },
];
const DECK_SLIDES_BY_FILE = new Map(DECK_SLIDES.map((s) => [s.file, s]));

// ---------------------------------------------------------------------------
// Filename parsing (the `PROJECT_NN_Description` convention from the usage
// block above).
// ---------------------------------------------------------------------------

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/_/g, '-')
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// A segment counts as part of the ALL-CAPS project prefix if it contains at
// least one letter and is already fully uppercase (so a bare numeric segment
// never matches here — that's handled by the digit-scan below instead).
function isAllCapsSegment(seg) {
  return /[A-Za-z]/.test(seg) && seg === seg.toUpperCase();
}

// `SOFIA_09_Urban_Portrait` -> { rawPrefix: 'SOFIA', nn: '09', descriptorRaw: 'Urban_Portrait', ... }
// `WITHOUT_ME_Original_Cover` (no numeric segment) -> { rawPrefix: 'WITHOUT_ME', nn: '01', descriptorRaw: 'Original_Cover', ... }
function deriveParts(baseName) {
  const segments = baseName.split('_').filter(Boolean);
  const digitIdx = segments.findIndex((s) => /^\d{1,3}$/.test(s));

  let prefixSegs;
  let nn;
  let descriptorSegs;

  if (digitIdx !== -1) {
    prefixSegs = segments.slice(0, digitIdx);
    nn = segments[digitIdx].padStart(2, '0');
    descriptorSegs = segments.slice(digitIdx + 1);
  } else {
    let i = 0;
    while (i < segments.length && isAllCapsSegment(segments[i])) i += 1;
    prefixSegs = segments.slice(0, i);
    nn = '01';
    descriptorSegs = segments.slice(i);
  }

  const rawPrefix = prefixSegs.join('_');
  const descriptorRaw = descriptorSegs.join('_') || baseName;
  const label = descriptorRaw.replace(/_/g, ' ');
  const nameSlug = slugify(descriptorRaw);

  return { rawPrefix, nn, nameSlug, label };
}

// Applies PREFIX_ALIASES, falling back to a `studio` slug when no project
// prefix could be determined at all (rather than throwing).
function resolveSlug(rawPrefix, sourcePath) {
  if (!rawPrefix) {
    console.warn(`  [warn] Could not determine a project prefix for "${path.basename(sourcePath)}" — using slug "studio".`);
    return 'studio';
  }
  const derived = slugify(rawPrefix);
  return PREFIX_ALIASES[derived] ?? derived;
}

function categoryOverrideFor(rawPrefix, defaultCategory) {
  const hit = CATEGORY_OVERRIDES.find((o) => rawPrefix === o.prefix || rawPrefix.startsWith(o.prefix + '_'));
  return hit ? hit.category : defaultCategory;
}

// ---------------------------------------------------------------------------
// Conversion
// ---------------------------------------------------------------------------

async function dominantColorHex(image) {
  const { data } = await image
    .clone()
    .removeAlpha()
    .resize(1, 1, { fit: 'fill' })
    .raw()
    .toBuffer({ resolveWithObject: true });
  const [r, g, b] = data;
  return '#' + [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('');
}

// Full-size filename -> small-variant filename, by inserting SMALL_SUFFIX
// before the extension (`foo.webp` -> `foo-800.webp`).
function smallVariantPath(outPath) {
  const ext = path.extname(outPath);
  return `${outPath.slice(0, -ext.length)}${SMALL_SUFFIX}${ext}`;
}

async function convertOne(sourcePath, outPath) {
  await fs.mkdir(path.dirname(outPath), { recursive: true });
  const image = sharp(sourcePath);
  const dom = await dominantColorHex(image);
  const info = await image
    .clone()
    .resize({ width: MAX_EDGE, height: MAX_EDGE, fit: 'inside', withoutEnlargement: true })
    .webp(WEBP_OPTIONS)
    .toFile(outPath);

  let small = null;
  if (Math.max(info.width, info.height) > SMALL_MAX_EDGE) {
    const smallOutPath = smallVariantPath(outPath);
    const smallInfo = await image
      .clone()
      .resize({ width: SMALL_MAX_EDGE, height: SMALL_MAX_EDGE, fit: 'inside', withoutEnlargement: true })
      .webp(WEBP_OPTIONS)
      .toFile(smallOutPath);
    small = { src: smallOutPath, w: smallInfo.width, h: smallInfo.height };
  }

  return { w: info.width, h: info.height, dom, small };
}

// ---------------------------------------------------------------------------
// Job collection
// ---------------------------------------------------------------------------

// Recursively finds every directory under `dir` whose name starts with a
// known "NN_" category prefix (01/02/03/04 — see CATEGORY_BY_DIR_PREFIX).
// Nesting above the matched directory is unconstrained, so both a shallow
// `_source/01_Foo/` and a deeply-nested drop folder work the same way.
async function findCategoryDirs(dir) {
  const results = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const abs = path.join(dir, entry.name);
    const m = entry.name.match(/^(\d{2})_/);
    if (m && CATEGORY_BY_DIR_PREFIX[m[1]]) {
      results.push({ absDir: abs, category: CATEGORY_BY_DIR_PREFIX[m[1]] });
      continue; // treat matched dirs as leaves; don't also scan inside them
    }
    results.push(...(await findCategoryDirs(abs)));
  }
  return results;
}

async function collectBulkJobs() {
  const jobs = [];
  const categoryDirs = (await findCategoryDirs(SOURCE_ROOT)).sort((a, b) => a.absDir.localeCompare(b.absDir));

  for (const { absDir, category: defaultCategory } of categoryDirs) {
    const entries = await fs.readdir(absDir);
    const images = entries.filter((f) => IMAGE_EXT_RE.test(f)).sort();
    for (const file of images) {
      const baseName = file.replace(IMAGE_EXT_RE, '');
      const { rawPrefix, nn, nameSlug, label } = deriveParts(baseName);
      const sourcePath = path.join(absDir, file);
      const slug = resolveSlug(rawPrefix, sourcePath);
      const category = categoryOverrideFor(rawPrefix, defaultCategory);
      jobs.push({ sourcePath, slug, category, nn, nameSlug, label });
    }
  }
  return jobs;
}

async function collectDeckJobs() {
  const jobs = [];
  let entries;
  try {
    entries = await fs.readdir(SOURCE_ROOT, { withFileTypes: true });
  } catch {
    return jobs;
  }
  const files = entries.filter((e) => e.isFile() && IMAGE_EXT_RE.test(e.name)).map((e) => e.name).sort();

  for (const file of files) {
    const override = DECK_SLIDES_BY_FILE.get(file);
    if (override) {
      jobs.push({
        sourcePath: path.join(SOURCE_ROOT, file),
        slug: override.slug,
        category: 'deck',
        nn: override.nn,
        nameSlug: override.descriptor,
        label: override.label,
      });
      continue;
    }

    // Not in the explicit override table — derive it from the filename like
    // any other source image. Never throws: worst case is a `studio` slug.
    const baseName = file.replace(IMAGE_EXT_RE, '');
    const { rawPrefix, nn, nameSlug, label } = deriveParts(baseName);
    const sourcePath = path.join(SOURCE_ROOT, file);
    const slug = resolveSlug(rawPrefix, sourcePath);
    console.warn(`  [warn] "${file}" is not in DECK_SLIDES — derived slug "${slug}", key "${nn}-${nameSlug}".`);
    jobs.push({ sourcePath, slug, category: 'deck', nn, nameSlug, label });
  }
  return jobs;
}

async function main() {
  try {
    await fs.access(SOURCE_ROOT);
  } catch {
    console.log(`No "_source/" directory found at ${SOURCE_ROOT} — nothing to do.`);
    return;
  }

  const jobs = [...(await collectBulkJobs()), ...(await collectDeckJobs())];
  if (jobs.length === 0) {
    console.log('No source images found under "_source/" — nothing to do.');
    return;
  }
  console.log(`Found ${jobs.length} source images to convert.`);

  const manifest = {};
  const seenOutputs = new Set();
  let processed = 0;
  const failures = [];

  for (const job of jobs) {
    const filename = `${job.category}-${job.nn}-${job.nameSlug}.webp`;
    const outPath = path.join(OUTPUT_ROOT, job.slug, filename);
    const webSrc = `/work/${job.slug}/${filename}`;

    if (seenOutputs.has(outPath)) {
      failures.push({ file: job.sourcePath, error: `Duplicate output path: ${outPath}` });
      continue;
    }
    seenOutputs.add(outPath);

    try {
      const { w, h, dom, small } = await convertOne(job.sourcePath, outPath);

      const entry = {
        src: webSrc,
        w,
        h,
        key: `${job.nn}-${job.nameSlug}`,
        label: job.label,
        dom,
      };
      if (small) {
        entry.sm = webSrc.replace(/\.webp$/, `${SMALL_SUFFIX}.webp`);
        entry.smW = small.w;
      }

      manifest[job.slug] ??= {};
      manifest[job.slug][job.category] ??= [];
      manifest[job.slug][job.category].push(entry);

      processed += 1;
      process.stdout.write(`\r  converted ${processed}/${jobs.length}`);
    } catch (err) {
      failures.push({ file: job.sourcePath, error: err.message });
    }
  }
  process.stdout.write('\n');

  // Sort each category array ascending by key, drop nothing (emptiness is
  // handled naturally since arrays are only created when a job lands in them).
  for (const slug of Object.keys(manifest)) {
    for (const category of Object.keys(manifest[slug])) {
      manifest[slug][category].sort((a, b) => a.key.localeCompare(b.key));
    }
  }

  await fs.mkdir(path.dirname(MANIFEST_PATH), { recursive: true });
  await fs.writeFile(MANIFEST_PATH, JSON.stringify(manifest, null, 2) + '\n');

  console.log(`Wrote manifest: ${MANIFEST_PATH}`);
  console.log(`Processed ${processed} images (${failures.length} failures).`);
  if (failures.length) {
    console.error('Failures:');
    for (const f of failures) console.error(`  ${f.file}: ${f.error}`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
